# Generated by Django 3.2.5 on 2021-07-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios1',
        ),
        migrations.DeleteModel(
            name='Professores',
        ),
    ]
