# Generated by Django 3.2.5 on 2021-07-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0004_alter_professores_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professores',
            options={'ordering': ('name',)},
        ),
    ]
