# Generated by Django 3.2.4 on 2021-07-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0005_alter_professores_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='info',
            field=models.TextField(default='Nada', max_length=455),
        ),
    ]
